name: CExporter Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'FFXIVClientStructs/**/*.cs'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Run CExporter
        working-directory: ./ida
        run: dotnet run --project CExporter/CExporter.csproj -c Release
      - name: Tar CExport
        run: tar -czvf CExport.tar.gz ./ida/*.h
      - uses: actions/upload-artifact@v4
        with:
          name: CExport
          path: CExport.tar.gz
          retention-days: 7
